import os
import sys
import time
###############
os.system("clear")

v = "\033[1;91m"

def banner () :
    print (' ')
    print ('''         \033[1;91m                         __    _''')
    print ('''                            _wr""        "-q__''')
    print ('''                          _dP                 9m_''')
    print ('''                        _#P                     9#_''')
    print ('''                       d#@                       9#m''')
    print ('''                      d##                         ###''')
    print ('''                     J###                         ###L''')
    print ('''                     {###K                       J###K''')
    print ('''                     ]####K     \033[1;90m ___aaa___\033[1;91m      J####F''')
    print ('''                 __gmM######_ \033[1;90m w#P""   ""9#m\033[1;91m  _d#####Mmw__''')
    print ('''              _g##############\033[1;90mmZ_\033[1;91m         __g##############m_''')
    print ('''            _d####M@PPPP@@M#######Mmp gm#########@@PPP9@M####m_''')
    print ('''           a###""         \033[1;90m ,Z\033[1;91m"#####@" '######\033[1;90m"\g\033[1;91m          ""M##m''')
    print ('''          J#@"            \033[1;90m 0L\033[1;91m  "*##     ##@" \033[1;90m J#\033[1;91m              *#K''')
    print ('''          #"              \033[1;90m `#\033[1;91m    "_gmwgm_~   \033[1;90m dF\033[1;91m               `#_''')
    print ('''         7F                \033[1;90m "#_\033[1;91m   ]#####F  \033[1;90m _dK\033[1;91m                 JE''')
    print ('''         ]                   \033[1;90m *m__\033[1;91m #####\033[1;90m __g@"\033[1;91m                   F''')
    print ('''                               \033[1;90m "PJ\033[1;91m#####\033[1;90mLP" ''')
    print ('''         \033[1;91m `                       0######_                      ' ''')
    print ('''                                _0########_''')
    print ('''              .               _d#####^#####m__              ,''')
    print ('''               "*w_________am#####P"   ~9#####mw_________w*"''')
    print ('''                   ""9@#####@M""           ""P@#####@M""''')
    print ('')
    print ("\033[1;90m  ************************************************************************  ")
banner ()
print ("\033[1;91m  *****************************\033[1;90m*MONSTER FBI\033[1;91m*******************************  ")
print ("\033[1;90m  ************************************************************************  ")
######
def banner1 () :

    print (" ")
    print ("\033[1;91m  *****************************\033[1;90m*MONSTER FBI\033[1;91m*******************************  ")
    print ('''\033[1;91m  ########::'########:'########::'########::'#######::'##::: ##:'########:''')
    print ('''  ##.... ##: ##.....:: ##.... ##:..... ##::'##.... ##: ###:: ##: ##.....::''')
    print ('''  ##:::: ##: ##::::::: ##:::: ##::::: ##::: ##:::: ##: ####: ##: ##:::::::''')
    print ('''  ########:: ######::: ##:::: ##:::: ##:::: ##:::: ##: ## ## ##: ######:::''')
    print ('''  ##.. ##::: ##...:::: ##:::: ##::: ##::::: ##:::: ##: ##. ####: ##...::::''')
    print ('''  ##::. ##:: ##::::::: ##:::: ##:: ##:::::: ##:::: ##: ##:. ###: ##:::::::''')
    print ('''  ##:::. ##: ########: ########:: ########:. #######:: ##::. ##: ########:''')
    print (''' \033[1;90m..:::::..::........::........:::........:::.......:::..::::..::...........::''')
    print ("              \033[1;92m ***\033[1;91m Coded By The owner\033[1;92m {MONSTER FBI}\033[1;91m\033[1;92m *** ")
    print ('')
banner1 ()
print ('')
print ("Login with Your password and username")
print ('')                                                                                                                                   print ('')
name = input ("username: ")                                                                                                                  name1 = input ("password: ")
print ("Login ...")
time.sleep(5)
os.system("clear")
print ('')
print ('')
banner1 ()
print ('')
print ('')
print ("Welcome\033[1;92m @"+name)
print ('')
print ("\033[1;91mWARNING !!! Make A last Before The increaseing Score")
print ('')
print ('')
print ("\033[1;91m*****************************\033[1;90m*MONSTER FBI\033[1;91m*******************************  ")
print ("[\033[1;90m1]\033[1;91m Spam Account")
print ("[\033[1;90m2]\033[1;91m increase Snapchat score")
print ("[\033[1;90m3]\033[1;91m Spam Report Highlight ")
print ("[\033[1;90m4]\033[1;91m Spam chat 'Coming Soon ")
print ("\033[1;91m*****************************\033[1;90m*MONSTER FBI\033[1;91m*******************************  ")
print ('')
print ('')
name2 =input ('\033[1;92m=>: ')
print ('')
print ('')
print ('')
print ("\033[1;92mHighlight Report Is Starting ...")

time.sleep(3)
os.system("clear")
banner1 ()
Target = input ("\033[1;92mTarget username: ")
v3 = ("\033[1;91m Highlight ")
time.sleep(0.3)
os.system("clear")
print ('')
banner1 ()
print ('                    King Of snapchat MONSTER FBI ✓')
print ('                Add me on snapchat For More @x.monster3')
print ('\033[1;91m                   ***Red Zone** Always in The Top')
print ('')
while True:
    time.sleep(1)
    done = 1
    print ("\033[1;91mReport Sended To \033[1;92m@"+Target+v3)
